[build]
  command = "yarn build"
  functions = "./dist/apps/detalluz-lambda"
  publish = "./dist/apps/detalluz-app"


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/es/*"
  to = "/es/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/es/index.html"
  status = 200
